Opgops 1493
ministryofjustice/opg-docker pull request #100
Opened 2016-09-27 12:04 UTC by brettminnie

Just the build tools, will do the build slaves next

2016-09-27 12:09 UTC, brettminnie commented on jenkins/Dockerfile
> +ENV JENKINS_VERSION ${JENKINS_VERSION:-2.7.4}
Just need to confirm the version here

2016-10-03 14:32 UTC, tim-mcarthur-moj requested changes

2016-10-03 14:32 UTC, tim-mcarthur-moj commented on jenkins/Dockerfile
> +    docker-engine \
pin this version to pre 1.11 as it won't work with v1 registry

2016-10-03 14:46 UTC, tim-mcarthur-moj approved these changes

2016-10-03 14:46 UTC, merged