WIP OPGOPS-1808
ministryofjustice/opg-docker pull request #138
Opened 2017-05-04 15:49 UTC by carinadigital

2017-05-04 15:51 UTC, carinadigital commented
Test run https://jenkins.service.opg.digital/job/OPG/job/docker-build-base/162/console

2017-05-05 09:30 UTC, tim-mcarthur-moj requested changes
There is a lot missing compared to the current jenkins 1 image.  This should just be an updated version of the original, with relevant changes for jenkins 2

2017-05-05 09:30 UTC, tim-mcarthur-moj commented on jenkins2/Dockerfile
> +ENV TINI_VERSION 0.14.0
this should use the same service startup process as other images using /etc/sv and my_init

2017-05-05 09:40 UTC, carinadigital commented on jenkins2/Dockerfile
> +ENV TINI_VERSION 0.14.0
I was trying to maintain the upstream structure for easy upgrade. Looks like that's not going to fly.

2017-05-05 09:52 UTC, merged