OPGOPS-1808 Jenkins2 container
ministryofjustice/opg-docker pull request #140
Opened 2017-05-08 15:17 UTC by carinadigital

2017-05-08 15:24 UTC, carinadigital commented on jenkins2/Dockerfile
> +      libgmp3-dev \
Not sure if all the packages are needed, as I've remove meta-compose and docker-machine from the container.

2017-05-08 15:32 UTC, brettminnie requested changes

2017-05-08 15:32 UTC, brettminnie commented on jenkins2/Dockerfile
> +      libgmp3-dev \
iirc these are needed to build the python bits and pieces

2017-05-08 15:32 UTC, brettminnie commented on jenkins2/Dockerfile
> +ARG JENKINS_SHA=aa7f243a4c84d3d6cfb99a218950b8f7b926af7aa2570b0e1707279d464472c7
Can you not pull this dynamically? If you use a different Jenkins version this will change

2017-05-08 15:32 UTC, brettminnie commented on jenkins2/plugins.sh
> +echo "WARN: plugins.sh is deprecated, please switch to install-plugins.sh"
If this is deprecated remove it

2017-05-08 15:33 UTC, carinadigital commented on jenkins2/Dockerfile
> +ARG JENKINS_SHA=aa7f243a4c84d3d6cfb99a218950b8f7b926af7aa2570b0e1707279d464472c7
I think that's the point. You move from known version to known version via human intervention, not automatic.

2017-05-08 15:34 UTC, carinadigital commented on jenkins2/plugins.sh
> +echo "WARN: plugins.sh is deprecated, please switch to install-plugins.sh"
It's like that in the upstream, but it supports both in the current build.
We can remove it if we like.

2017-05-09 07:18 UTC, tim-mcarthur-moj requested changes

2017-05-09 07:18 UTC, tim-mcarthur-moj commented on jenkins2/init.groovy
> +      println "--> setting agent port for jnlp... done"
we should also be setting the tz to Europe/London so job timestamps are not in utc

https://wiki.jenkins-ci.org/display/JENKINS/Change+time+zone

2017-05-09 07:18 UTC, tim-mcarthur-moj commented on jenkins2/Dockerfile
> +###RUN groupmod -g 497 docker && adduser ${user} docker
where is the jenkins user getting access to the docker socket from.

2017-05-09 07:18 UTC, tim-mcarthur-moj commented on Makefile
>  oldRegistryUrl = registry.service.dsd.io
oldRegistryUrl is no longer needed

2017-05-09 12:54 UTC, carinadigital commented on jenkins2/init.groovy
> +      println "--> setting agent port for jnlp... done"
so leave the container as UTC and put jenkins into Europe/London ?

2017-05-09 12:57 UTC, carinadigital commented on Makefile
>  oldRegistryUrl = registry.service.dsd.io
That's the top level Makefile. Are you sure we aren't  using dsd.io anywhere now?

2017-05-09 13:42 UTC, carinadigital commented on jenkins2/plugins.sh
> +echo "WARN: plugins.sh is deprecated, please switch to install-plugins.sh"
Removed

2017-05-09 13:42 UTC, carinadigital commented on jenkins2/init.groovy
> +      println "--> setting agent port for jnlp... done"
Done.

2017-05-09 13:46 UTC, carinadigital commented on jenkins2/Dockerfile
> +###RUN groupmod -g 497 docker && adduser ${user} docker
Removing upstream fix. ECS specific

2017-05-09 14:27 UTC, brettminnie approved these changes
lgtm

2017-05-09 17:07 UTC, carinadigital commented
Test jenkins run https://jenkins.service.opg.digital/job/OPG/job/docker-build-base/168/

2017-05-10 07:50 UTC, tim-mcarthur-moj commented on Makefile
>  oldRegistryUrl = registry.service.dsd.io
yes

2017-05-10 14:28 UTC, carinadigital commented
Rebases and jenkins rerun https://jenkins.service.opg.digital/job/OPG/job/docker-build-base/179/

2017-05-10 14:33 UTC, Azulinho commented on jenkins2/Dockerfile
> +ARG JENKINS_SHA=aa7f243a4c84d3d6cfb99a218950b8f7b926af7aa2570b0e1707279d464472c7
+1

2017-05-10 14:37 UTC, tim-mcarthur-moj requested changes

2017-05-10 14:37 UTC, tim-mcarthur-moj commented on Makefile
> +CHILD_CONTAINERS := phpunit golang rabbitmq wordpress elasticsearch elasticsearch-shared-data jenkins-slave jenkins jenkins2 kibana nginx-router wkhtmlpdf nginx-redirect casperjs  mongodb elasticsear
jenkins can be removed from the image list now as we don't need to update the latest build

2017-05-10 14:37 UTC, tim-mcarthur-moj commented on jenkins2/docker-compose.yml
> +      -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/London \
these settings won't make it into the deployed container.

2017-05-10 14:37 UTC, tim-mcarthur-moj commented on jenkins2/docker-compose.yml
> +    - "8080:8080"
did you look at enabling ssl for the elb -> container

2017-05-10 14:40 UTC, carinadigital commented on jenkins2/docker-compose.yml
> +      -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/London \
This is intentional. The docker-compose will template for salt will have this config in it.

2017-05-10 14:42 UTC, carinadigital commented on jenkins2/docker-compose.yml
> +    - "8080:8080"
SSL elb offloading will still work 443:8080 . Since local testing is without SSL, I just left it on the port the container runs on.

2017-05-10 14:42 UTC, carinadigital commented on jenkins2/docker-compose.yml
> +      -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/London \
And later ansible will have this config.

2017-05-10 14:44 UTC, carinadigital commented on Makefile
> +CHILD_CONTAINERS := phpunit golang rabbitmq wordpress elasticsearch elasticsearch-shared-data jenkins-slave jenkins jenkins2 kibana nginx-router wkhtmlpdf nginx-redirect casperjs  mongodb elasticsear
Removed

2017-05-11 09:41 UTC, tim-mcarthur-moj commented on jenkins2/docker-compose.yml
> +    - "8080:8080"
enabling ssl for the elb -> jenkins connection is in the unwritten backlog. please make it secure by default

2017-05-11 10:01 UTC, Azulinho commented on jenkins2/docker-compose.yml
> +    - "8080:8080"
just a reminder that jnlp doesn't talk http, keep that in mind when encrypting traffic from the slaves

2017-05-12 07:58 UTC, tim-mcarthur-moj approved these changes

2017-05-12 08:01 UTC, merged