Opgops 1935
ministryofjustice/opg-docker pull request #141
Opened 2017-05-09 19:32 UTC by brettminnie

0x644 Images

2017-05-10 06:47 UTC, tim-mcarthur-moj requested changes

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on base0x644/Dockerfile
> +RUN  rm -f /etc/apt/sources.list.d/* && \
we should switch to using apt

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on base0x644/Dockerfile
> +RUN  wget -O /usr/bin/confd https://github.com/kelseyhightower/confd/releases/download/v0.9.0/confd-0.9.0-linux-amd64 && \
update to use latest stable 0.11 version

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on base0x644/docker/beaver.conf
> +tags: ebs-snapshot, master
why is the master tag in here? should this not be changed to include the stack tag as per the other log file configs for beaver

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on nginx0x644/Dockerfile
> +RUN  apt-get install -y libpcre3-dev zlib1g-dev libssl-dev libossp-uuid-dev uuid && \
change to using apt command

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on nginx0x644/Makefile
> +oldRegistryUrl ?= registry.service.dsd.io
can be removed

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on nginx0x644/Makefile
> +	docker tag "$(registryUrl)/$(image)" "$(registryUrl)/$(image):$(newtag)"
remove all refs to old registry

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on nginx0x644/docker/nginx/nginx.conf
> +worker_processes  1;
this should be templated

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on nginx0x644/docker/service/nginx/run
> +mkdir -p /var/log/app
this is done by base, so isn't needed

2017-05-10 06:47 UTC, tim-mcarthur-moj commented on php-fpm0x644/docker/confd/templates/pool.app.conf.tmpl
> +pm.max_children = {{getv "/opg/php/pool/children/max"}}
this should have a sane default

2017-05-10 07:03 UTC, brettminnie commented on base0x644/Dockerfile
> +RUN  rm -f /etc/apt/sources.list.d/* && \
apt raises a cli warning at present

2017-05-10 09:01 UTC, brettminnie commented on base0x644/docker/beaver.conf
> +tags: ebs-snapshot, master
Direct import for now, I am going to review

2017-05-10 09:02 UTC, brettminnie commented on nginx0x644/Makefile
> +	docker tag "$(registryUrl)/$(image)" "$(registryUrl)/$(image):$(newtag)"
See OPGOPS-1937

2017-05-10 09:02 UTC, brettminnie commented on nginx0x644/docker/nginx/nginx.conf
> +worker_processes  1;
Most of these should be, I'll review today

2017-05-24 13:05 UTC, tim-mcarthur-moj approved these changes

2017-05-24 13:14 UTC, brettminnie commented
Closing this as we're moving to the separate repo

2017-05-24 13:14 UTC, closed without merging